default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sn-blog_development

test:
  <<: *default
  database: sn-blog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
