# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d95d6e068a566156753e03d4c923db7abb0cfd3643f7aa667788e3e4158935b4de5d4cd4633212bcb47e1649a26a2150cc56fda303ec548418003c6572e9aa

test:
  secret_key_base: 54a01683b2533880a25ae14f98ced96f74297f5ae9dd2913847348f5964967233feac9eee8c0abee2418094998d2061838fe28d5acc51578af76ab4f9a070dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
